### ISSUE TITLE
should this be using rel=feed?

### ISSUE THREAD

**Issue by dbaron** [WICG/media-feeds#30]
This draft seems to be proposing a new-ish link relation type, `feed`.  Typically feeds have been linked as `<link rel=alternate>`.  HTML5 did have a `feed` relation type for a bit, but it was [removed](https://lists.w3.org/Archives/Public/public-whatwg-archive/2009Oct/0206.html) in 2009.  It's not in the [link relations registry](https://www.iana.org/assignments/link-relations/link-relations.xhtml) and it's in one of the lower sections of the [existing rel values](http://microformats.org/wiki/existing-rel-values) list which is [referenced by HTML](https://html.spec.whatwg.org/multipage/#other-link-types).

It's also not clear that what this draft is proposing matches the typical meaning of a "feed", which I think is more typically a chronological list of posts in some sequence, generally either representing a complete sequence of some work or curated in some way, rather than a set of automated recommendations.

These two things make me wonder if `rel=feed` is the right thing here.

(I got here from w3ctag/design-reviews#477.)

**Comment by beccahughes** [comment]
How about if we added a `rel=media-feed` type?

**Comment by kevinmarks** [comment]
The complete [rel registry](http://microformats.org/wiki/existing-rel-values) includes `rel=feed` as a draft. Certainly `rel=alternate` is wrong, as what is proposed is not an alternative version fo the current page. I don't think rel=media-feed makes sense either. Something like `rel=suggested-videos` is closest to what this is aiming for.

**Comment by beccahughes** [comment]
Why would rel=media-feed not make sense?

**Comment by beccahughes** [comment]
@kevinmarks to follow up I think the reason why `rel=media-feed` makes sense here is the name of the spec is media feeds and using "suggested-videos" could cause confusion and we also don't want to limit ourselves to just videos in the future

**Comment by kevinmarks** [comment]
I suppose this is a critique of they overall name, as its not media feeds,
its suggested next media. As you have noted earlier, podcasts are media
feeds, and are more general, and there are already many ways of expressing
those.

You're using feed I'm the Facebook news feed sense, not the broader Web
sense.

I should probably file this as a separate issue, but if you want a JSON-LD
way to represent a stream of video suggestions, activity streams 2 can do
that with existing vocabulary.

**Comment by beccahughes** [comment]
The name of the spec comes from our use of [DataFeed](https://schema.org/DataFeed) from schema.org which defines itself as "A single feed providing structured information about one or more entities or topics.".

**Comment by beccahughes** [comment]
@kevinmarks I would like to add this proposal to http://microformats.org/wiki/existing-rel-values but it seems like account creation on the website is having some issues (broken recaptcha)?

**Comment by kevinmarks** [comment]
There's a server replacement effort going on at the moment, sorry about
that.

**Comment by beccahughes** [comment]
The spec has been updated and the new type is now in the IANA registry. I do plan to also add it to microformats.org when the server is fixed but I will file a separate issue for that
