### ISSUE TITLE
clarify there is no service worker FetchEvent

### ISSUE THREAD

**Issue by wanderview** [WICG/media-feeds#37]
I was asked recently if fetches from this effort would go through a service worker FetchEvent handler.  My interpretation of the spec is that it would not.  There is no client set on the fetch request, so there is no service worker controller.

Is this correct?  Maybe add a non-normative note indicating the intent there since its not obvious at first read?

Also, this matters for privacy since if a service worker FetchEvent were fired it would give the origin an opportunity to run javascript, store state, etc in the background.

**Comment by beccahughes** [comment]
Yes this does not go through service workers
