### ISSUE TITLE
Security/Privacy concerns

### ISSUE THREAD

**Issue by plinss** [WICG/media-feeds#41]
@chrisn Left some concerns in https://github.com/w3ctag/design-reviews/issues/477#issuecomment-652922928, which are shared by other members of the TAG.

It's unclear to us when the browser would be sending authenticated requests to a site to fetch a feed and how it would be indicated to a user that this is happening.

**Comment by beccahughes** [comment]
I have added some clarity to both the questionnaire and the spec around when a user agent is expected to gather consent. For Chromium, we gather a feature level consent and then show a notification to the user when new feeds are discovered with an option to opt-out.
